[build]
  command = "bash build.sh"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/vip/*"
  to = "/vip/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login/index.html"
  status = 200

[[redirects]]
  from = "/superadmin"
  to = "/admin/index.html"
  status = 302

[[redirects]]
  from = "/flyer-builder"
  to = "/flyer-builder/index.html"
  status = 200

[[redirects]]
  from = "/flyer-builder/*"
  to = "/flyer-builder/index.html"
  status = 200

[[redirects]]
  from = "/flyer-builder/review-sent"
  to = "/flyer-builder/review-sent/index.html"
  status = 200

[[redirects]]
  from = "/flyer-builder/review-sent/*"
  to = "/flyer-builder/review-sent/index.html"
  status = 200